version: '3'
volumes:
  data:
services:
  db:
    image: postgres:9.6
    volumes: 
      # Data Volume
      - data:/var/lib/postgresql/data
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql